version: '3'

services:
  orders-db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
